//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Controls/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""OnFoot"",
            ""id"": ""dbc6b227-a36a-41a6-b67f-35fd5515ef72"",
            ""actions"": [
                {
                    ""name"": ""Walk"",
                    ""type"": ""Value"",
                    ""id"": ""756775bc-ad7f-4dec-b635-2b3cd6e94dcb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MainSpell"",
                    ""type"": ""Button"",
                    ""id"": ""018d6f95-6c3c-4f06-8223-ceaa9c28b821"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecSpell"",
                    ""type"": ""Button"",
                    ""id"": ""08e7aaeb-f4bc-40dc-b751-c06ba9ba08f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePos"",
                    ""type"": ""Value"",
                    ""id"": ""ec5eeb86-4830-42da-9c42-92bdeff0317a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""94e186c8-54ef-4e5a-bd2a-8a8e8fe0e06d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""3f7e5444-6e06-4284-b463-53f2a7039baf"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""124c6266-78fa-458a-8915-abe2bfd5934c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""71ab86cb-b787-4d30-a58e-689077a28ca8"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e52af247-4ac5-4aed-bc80-1ed929fbd224"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""fce7825d-8dc6-405d-8976-9f034e4f32e3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MainSpell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea32bb33-ce6f-4333-8ccf-b89e70e01460"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecSpell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9fdea7cc-1413-40e6-82a5-861f66396729"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // OnFoot
        m_OnFoot = asset.FindActionMap("OnFoot", throwIfNotFound: true);
        m_OnFoot_Walk = m_OnFoot.FindAction("Walk", throwIfNotFound: true);
        m_OnFoot_MainSpell = m_OnFoot.FindAction("MainSpell", throwIfNotFound: true);
        m_OnFoot_SecSpell = m_OnFoot.FindAction("SecSpell", throwIfNotFound: true);
        m_OnFoot_MousePos = m_OnFoot.FindAction("MousePos", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // OnFoot
    private readonly InputActionMap m_OnFoot;
    private IOnFootActions m_OnFootActionsCallbackInterface;
    private readonly InputAction m_OnFoot_Walk;
    private readonly InputAction m_OnFoot_MainSpell;
    private readonly InputAction m_OnFoot_SecSpell;
    private readonly InputAction m_OnFoot_MousePos;
    public struct OnFootActions
    {
        private @PlayerControls m_Wrapper;
        public OnFootActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Walk => m_Wrapper.m_OnFoot_Walk;
        public InputAction @MainSpell => m_Wrapper.m_OnFoot_MainSpell;
        public InputAction @SecSpell => m_Wrapper.m_OnFoot_SecSpell;
        public InputAction @MousePos => m_Wrapper.m_OnFoot_MousePos;
        public InputActionMap Get() { return m_Wrapper.m_OnFoot; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OnFootActions set) { return set.Get(); }
        public void SetCallbacks(IOnFootActions instance)
        {
            if (m_Wrapper.m_OnFootActionsCallbackInterface != null)
            {
                @Walk.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnWalk;
                @Walk.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnWalk;
                @Walk.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnWalk;
                @MainSpell.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnMainSpell;
                @MainSpell.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnMainSpell;
                @MainSpell.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnMainSpell;
                @SecSpell.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSecSpell;
                @SecSpell.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSecSpell;
                @SecSpell.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSecSpell;
                @MousePos.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnMousePos;
                @MousePos.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnMousePos;
                @MousePos.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnMousePos;
            }
            m_Wrapper.m_OnFootActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Walk.started += instance.OnWalk;
                @Walk.performed += instance.OnWalk;
                @Walk.canceled += instance.OnWalk;
                @MainSpell.started += instance.OnMainSpell;
                @MainSpell.performed += instance.OnMainSpell;
                @MainSpell.canceled += instance.OnMainSpell;
                @SecSpell.started += instance.OnSecSpell;
                @SecSpell.performed += instance.OnSecSpell;
                @SecSpell.canceled += instance.OnSecSpell;
                @MousePos.started += instance.OnMousePos;
                @MousePos.performed += instance.OnMousePos;
                @MousePos.canceled += instance.OnMousePos;
            }
        }
    }
    public OnFootActions @OnFoot => new OnFootActions(this);
    public interface IOnFootActions
    {
        void OnWalk(InputAction.CallbackContext context);
        void OnMainSpell(InputAction.CallbackContext context);
        void OnSecSpell(InputAction.CallbackContext context);
        void OnMousePos(InputAction.CallbackContext context);
    }
}
